## operstion on dataframe

- filtering the dataframe
- single and multiple columns
- creating new columns
- Lambada function 
- Gorup by agrrigate function 
- pivat data
- Marging dataframe
- join and concatiations

## Preparatory steps
- Background
An FMCG company P&J found that the sales of their best selling items are affected by the weather and rainfall trend. For example, the sale of tea increases when it rains, sunscreen is sold on the days when it is least likely to rain, and the sky is clear. They would like to check whether the weather patterns play a vital role in the sale of certain items. Hence as initial experimentation, they would like you to forecast the weather trend in the upcoming days. The target region for this activity is Australia; accordingly, this exercise will be based on analysing and cleaning the weather data from the Australian region available on public platforms.

Read the data into a dataframe

In [41]:
import pandas as pd 
import numpy as np

In [42]:
# Read the data frame  
data = pd.read_csv("C:\\python.py\\Data\\weather data.csv")

In [43]:
data.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed
0,01-12-2008,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0
1,02-12-2008,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0
2,03-12-2008,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0
3,04-12-2008,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0
4,05-12-2008,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0

In [44]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 142193 entries, 0 to 142192
Data columns (total 9 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Date           142193 non-null  object
 1   Location       142193 non-null  object
 2   MinTemp        141556 non-null  float64
 3   MaxTemp        141871 non-null  float64
 4   Rainfall       140787 non-null  float64
 5   Evaporation    81350 non-null   float64
 6   Sunshine       74377 non-null   float64
 7   WindGustDir    132863 non-null  object
 8   WindGustSpeed  132923 non-null  float64
dtypes: float64(6), object(3)
memory usage: 9.8+ MB

In [45]:
data.shape

(142193, 9)

In [46]:
# filtering data shune more the 4 hours
data[data["Sunshine"]>4]

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed
5939,01-01-2009,Cobar,17.9,35.2,0.0,12.0,12.3,SSW,48.0
5940,02-01-2009,Cobar,18.4,28.9,0.0,14.8,13.0,S,37.0
5941,03-01-2009,Cobar,15.5,34.1,0.0,12.6,13.3,SE,30.0
5942,04-01-2009,Cobar,19.4,37.6,0.0,10.8,10.6,NNE,46.0
5943,05-01-2009,Cobar,21.9,38.4,0.0,11.4,12.2,WNW,31.0
...,...,...,...,...,...,...,...,...,...
139108,20-06-2017,Darwin,19.3,33.4,0.0,6.0,11.0,ENE,35.0
139109,21-06-2017,Darwin,21.2,32.6,0.0,7.6,8.6,E,37.0
139110,22-06-2017,Darwin,20.7,32.8,0.0,5.6,11.0,E,33.0
139111,23-06-2017,Darwin,19.5,31.8,0.0,6.2,10.6,ESE,26.0
139112,24-06-2017,Darwin,20.2,31.7,0.0,5.6,10.7,ENE,30.0

In [47]:
len(data[data["Sunshine"]>4])

58898

In [48]:
# The cold drink sales the will be most likely increse on the days which have high suncine(>5)
#and high max themp. (>35) use the operastion filter this days
data[(data["MaxTemp"]>35) & (data["Sunshine"]>5)]

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed
5939,01-01-2009,Cobar,17.9,35.2,0.0,12.0,12.3,SSW,48.0
5942,04-01-2009,Cobar,19.4,37.6,0.0,10.8,10.6,NNE,46.0
5943,05-01-2009,Cobar,21.9,38.4,0.0,11.4,12.2,WNW,31.0
5944,06-01-2009,Cobar,24.2,41.0,0.0,11.2,8.4,WNW,35.0
5948,10-01-2009,Cobar,19.0,35.5,0.0,12.0,12.3,ENE,48.0
...,...,...,...,...,...,...,...,...,...
138862,17-10-2016,Darwin,25.1,35.2,0.0,7.4,11.5,NNE,39.0
138879,03-11-2016,Darwin,24.4,35.5,0.0,7.8,9.9,NW,35.0
138892,16-11-2016,Darwin,25.7,35.2,0.0,5.4,11.3,NW,26.0
138905,29-11-2016,Darwin,25.8,35.1,0.8,4.8,6.4,SSE,46.0
138910,04-12-2016,Darwin,25.8,35.2,0.0,NaN,12.0,ESE,33.0

## creating new column
- if you notice the filtering done in the eleri example i did not the prisise infromation about the day
- if data coluam simply has the date 
- the date colum split in to the year,month,dates

In [49]:
# spacial modual dattime index
pd.DatetimeIndex(data["Date"])

DatetimeIndex(['2008-01-12', '2008-02-12', '2008-03-12', '2008-04-12',
               '2008-05-12', '2008-06-12', '2008-07-12', '2008-08-12',
               '2008-09-12', '2008-10-12',
               ...
               '2017-06-15', '2017-06-16', '2017-06-17', '2017-06-18',
               '2017-06-19', '2017-06-20', '2017-06-21', '2017-06-22',
               '2017-06-23', '2017-06-24'],
              dtype='datetime64[ns]', name='Date', length=142193, freq=None)

In [50]:
pd.DatetimeIndex(data["Date"]).year

Index([2008, 2008, 2008, 2008, 2008, 2008, 2008, 2008, 2008, 2008,
       ...
       2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017],
      dtype='int32', name='Date', length=142193)

In [51]:
pd.DatetimeIndex(data["Date"]).month

Index([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,
       ...
        6,  6,  6,  6,  6,  6,  6,  6,  6,  6],
      dtype='int32', name='Date', length=142193)

In [52]:
# to add new colum year
data["year"] = pd.DatetimeIndex(data["Date"]).year
data.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,year
0,01-12-2008,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,2008
1,02-12-2008,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,2008
2,03-12-2008,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,2008
3,04-12-2008,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,2008
4,05-12-2008,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,2008

In [53]:
# add month colum 
data["Month"] = pd.DatetimeIndex(data["Date"]).month
data.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,year,Month
0,01-12-2008,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,2008,1
1,02-12-2008,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,2008,2
2,03-12-2008,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,2008,3
3,04-12-2008,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,2008,4
4,05-12-2008,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,2008,5

In [54]:
# Add day colum 
data["Day"]= pd.DatetimeIndex(data["Date"]).day
data.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,year,Month,Day
0,01-12-2008,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,2008,1,12
1,02-12-2008,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,2008,2,12
2,03-12-2008,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,2008,3,12
3,04-12-2008,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,2008,4,12
4,05-12-2008,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,2008,5,12

In [55]:
data["maxtemp_f"] = data["MaxTemp"]*(9/5)+32

data.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,year,Month,Day,maxtemp_f
0,01-12-2008,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,2008,1,12,73.22
1,02-12-2008,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,2008,2,12,77.18
2,03-12-2008,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,2008,3,12,78.26
3,04-12-2008,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,2008,4,12,82.40
4,05-12-2008,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,2008,5,12,90.14

In [56]:
data.Rainfall

0         0.6
1         0.0
2         0.0
3         0.0
4         1.0
         ...
142188    0.0
142189    0.0
142190    0.0
142191    0.0
142192    0.0
Name: Rainfall, Length: 142193, dtype: float64

In [ ]:
# use lamda function 
# which creat new colum witch highligh the day witch have the rain fail more then >50mm as rainy days and the rest are not

data.Rainfall.apply(lambda x: "barish_hoti" if x > 50 else "barish_nahi_hoti" )

0         barish_nahi_hoti
1         barish_nahi_hoti
2         barish_nahi_hoti
3         barish_nahi_hoti
4         barish_nahi_hoti
                ...
142188    barish_nahi_hoti
142189    barish_nahi_hoti
142190    barish_nahi_hoti
142191    barish_nahi_hoti
142192    barish_nahi_hoti
Name: Rainfall, Length: 142193, dtype: object

In [60]:
data["Is_raning"] = data.Rainfall.apply(lambda x: "barish_hoti" if x >50 else "barish_nahi_hoti")

In [61]:
data.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,year,Month,Day,maxtemp_f,Is_raning
0,01-12-2008,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,2008,1,12,73.22,barish_nahi_hoti
1,02-12-2008,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,2008,2,12,77.18,barish_nahi_hoti
2,03-12-2008,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,2008,3,12,78.26,barish_nahi_hoti
3,04-12-2008,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,2008,4,12,82.40,barish_nahi_hoti
4,05-12-2008,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,2008,5,12,90.14,barish_nahi_hoti

In [62]:
data[data["Is_raning"]== "barish_hoti"]

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,year,Month,Day,maxtemp_f,Is_raning
429,05-02-2010,Albury,19.2,26.1,52.2,NaN,NaN,SE,33.0,2010,5,2,78.98,barish_hoti
455,08-03-2010,Albury,18.1,25.5,66.0,NaN,NaN,NW,56.0,2010,8,3,77.90,barish_hoti
690,31-10-2010,Albury,13.8,18.7,50.8,NaN,NaN,NNW,52.0,2010,10,31,65.66,barish_hoti
704,14-11-2010,Albury,19.2,22.6,52.6,NaN,NaN,N,26.0,2010,11,14,72.68,barish_hoti
787,05-02-2011,Albury,20.4,23.0,99.2,NaN,NaN,NW,28.0,2011,5,2,73.40,barish_hoti
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140532,03-02-2017,Katherine,23.4,33.0,62.0,NaN,NaN,NNW,33.0,2017,3,2,91.40,barish_hoti
140571,14-03-2017,Katherine,23.0,35.0,79.0,31.0,NaN,ESE,22.0,2017,3,14,95.00,barish_hoti
140578,22-03-2017,Katherine,24.1,34.5,61.4,NaN,NaN,N,31.0,2017,3,22,94.10,barish_hoti
142013,26-12-2016,Uluru,22.1,27.4,83.8,NaN,NaN,ENE,72.0,2016,12,26,81.32,barish_hoti
142014,27-12-2016,Uluru,22.1,35.8,63.8,NaN,NaN,WNW,43.0,2016,12,27,96.44,barish_hoti

In [64]:
len(data[data["Is_raning"]== "barish_hoti"])

786

In [67]:
# Grouping and aggreation
# find the loction witch recived the most ammount rain the given data in this plase cartain promational offercan be put place to boost sales like tea,umbrella, etc


data_by_loction = data.groupby(by =["Location"]).mean(numeric_only= True)

data_by_loction

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,year,Month,Day,maxtemp_f
Location,,,,,,,,,,
Adelaide,12.628368,22.945402,1.572185,5.824924,7.752002,36.530812,2012.525890,6.522330,15.742071,73.301723
Albany,12.948461,20.072587,2.255073,4.207273,6.658765,NaN,2012.708554,6.451592,15.641910,68.130657
Albury,9.520899,22.630963,1.925710,NaN,NaN,32.953016,2012.733643,6.447360,15.711059,72.735734
AliceSprings,13.125182,29.244191,0.869355,9.029929,9.581944,40.533714,2012.719565,6.451006,15.645661,84.639545
BadgerysCreek,11.136900,24.023111,2.207925,NaN,NaN,33.609890,2012.790984,6.402322,15.693306,75.241600
Ballarat,7.355302,18.274794,1.688830,NaN,NaN,44.978695,2012.732166,6.463012,15.686592,64.894628
Bendigo,8.591065,21.616683,1.621452,3.851730,NaN,38.849283,2012.723138,6.459459,15.679960,70.910030
Brisbane,16.410998,26.441527,3.160536,5.408848,8.082782,28.211380,2012.496678,6.547928,15.727934,79.594748
Cairns,21.199197,29.544344,5.765317,6.211976,7.575995,38.067991,2012.677376,6.425368,15.658300,85.179819
Canberra,6.827688,20.980644,1.735038,4.404717,7.403241,40.082174,2012.164131,6.483616,15.714745,69.765160
Cobar,13.120342,25.834081,1.129262,6.720797,8.674364,36.728814,2012.766064,6.410977,15.619143,78.501346
CoffsHarbour,14.365774,23.915575,5.054592,3.904267,7.362374,39.232197,2012.749746,6.437521,15.671859,75.048035
Dartmoor,8.619816,19.694427,2.148554,3.353097,6.412715,38.896904,2012.857628,6.483860,15.724091,67.449969
Darwin,23.210530,32.540977,5.094048,6.319089,8.499310,40.582355,2012.502820,6.528822,15.722431,90.573759
GoldCoast,17.341490,25.752971,3.728933,NaN,NaN,42.472539,2012.683221,6.469799,15.683221,78.355347
Hobart,9.079141,17.866677,1.604273,3.601226,6.578324,47.531398,2012.502196,6.527604,15.728356,64.160019
Katherine,20.534983,34.939037,3.135599,7.333198,NaN,38.758328,2014.827453,6.424631,15.603592,94.890267
Launceston,7.833818,18.956231,2.012219,6.166667,NaN,35.630877,2012.723250,6.458388,15.657860,66.121217
Melbourne,11.788127,20.860148,1.837772,4.595893,6.465776,45.425444,2011.949897,6.635318,15.834497,69.548266
MelbourneAirport,9.973945,20.491858,1.451977,4.644378,6.381283,46.919172,2012.779661,6.419076,15.646726,68.885344
Mildura,10.733954,24.841536,0.945025,5.935952,8.468104,37.170829,2012.778849,6.420353,15.642833,76.714766
Moree,12.786255,26.886861,1.603296,7.629964,8.896590,39.799425,2012.688858,6.454800,15.502453,80.396349
MountGambier,8.827468,19.828128,2.087359,3.437072,6.511167,42.869099,2012.717822,6.455776,15.668317,67.690631
MountGinini,3.651193,11.777947,3.245241,NaN,NaN,46.188214,2012.835225,6.463364,15.654627,53.200304
Newcastle,13.740240,24.098283,3.153022,NaN,NaN,NaN,2012.706599,6.487310,15.662267,75.376909
Nhil,8.992798,22.398407,0.932907,NaN,NaN,42.542438,2014.838751,6.418738,15.687699,72.317132
NorahHead,15.375197,22.607900,3.382479,NaN,NaN,42.215043,2012.804712,6.391260,15.688290,72.694220
NorfolkIsland,16.839960,21.792746,3.137568,4.738026,7.021751,42.639973,2012.724696,6.413630,15.622470,71.226943
Nuriootpa,9.366433,21.714658,1.381375,5.084132,7.675888,40.660720,2012.776482,6.414057,15.650899,71.086384
PearceRAAF,12.386314,26.271049,1.634354,NaN,8.894160,43.448549,2012.840333,6.347936,15.598479,79.287888
Penrith,12.533649,24.731984,2.135143,NaN,NaN,31.794386,2012.763158,6.445682,15.647436,76.517571
Perth,12.922706,25.034837,1.906295,5.606579,8.784536,34.882999,2012.504228,6.528656,15.725337,77.062707
PerthAirport,12.580359,25.533234,1.761648,5.662832,8.795306,44.201822,2012.779661,6.419076,15.646726,77.959821
Portland,9.585537,18.055626,2.531032,3.421514,6.496751,42.058883,2012.778037,6.415554,15.661883,64.500127
Richmond,11.346070,24.449813,2.152581,5.259336,NaN,34.860354,2012.802779,6.426296,15.604880,76.009664
Sale,8.561220,20.271024,1.512667,3.830098,6.683663,42.474529,2012.771000,6.415000,15.666333,68.487843
SalmonGums,9.302578,24.249204,1.032302,NaN,NaN,39.761086,2012.814552,6.429442,15.642301,75.648567
Sydney,14.865057,23.002339,3.330231,5.187432,7.179374,41.761408,2012.300869,6.453102,15.665868,73.404210
SydneyAirport,14.894041,23.378902,2.995335,5.252450,7.198126,47.222072,2012.774709,6.420965,15.645923,74.082023
Townsville,20.411250,29.362974,3.488603,7.197113,8.460627,38.804052,2012.724036,6.453347,15.661391,84.853353
Tuggeranong,7.245612,20.777444,2.159040,NaN,NaN,35.189615,2012.741494,6.453969,15.665777,69.399399
Uluru,14.406983,30.387442,0.707324,NaN,NaN,41.369231,2014.852728,6.468113,15.691650,86.697396
WaggaWagga,9.562030,22.961290,1.706085,5.159061,8.197864,36.566147,2012.736559,6.415659,15.642809,73.330323
Walpole,11.915711,20.566821,2.877329,NaN,NaN,39.753051,2012.819794,6.359347,15.650585,69.020277
Watsonia,10.126228,20.883528,1.847692,4.640788,6.378152,38.057297,2012.770590,6.422808,15.649216,69.590350
Williamtown,12.820376,24.147020,3.510985,6.957167,7.140044,41.753695,2012.704269,6.397571,15.815511,75.464635
Witchcliffe,10.756861,21.699423,2.899658,NaN,NaN,39.980259,2012.781504,6.428523,15.653794,71.058962
Wollongong,14.949058,21.476510,3.589127,NaN,NaN,45.695257,2012.743882,6.465974,15.652028,70.657718
Woomera,13.313898,26.542135,0.489946,10.116654,9.063005,44.080962,2012.773579,6.402676,15.634448,79.775843

In [68]:
len(data_by_loction)

49

In [70]:
data_by_loction.sort_values("Rainfall",ascending = False)

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,year,Month,Day,maxtemp_f
Location,,,,,,,,,,
Cairns,21.199197,29.544344,5.765317,6.211976,7.575995,38.067991,2012.677376,6.425368,15.658300,85.179819
Darwin,23.210530,32.540977,5.094048,6.319089,8.499310,40.582355,2012.502820,6.528822,15.722431,90.573759
CoffsHarbour,14.365774,23.915575,5.054592,3.904267,7.362374,39.232197,2012.749746,6.437521,15.671859,75.048035
GoldCoast,17.341490,25.752971,3.728933,NaN,NaN,42.472539,2012.683221,6.469799,15.683221,78.355347
Wollongong,14.949058,21.476510,3.589127,NaN,NaN,45.695257,2012.743882,6.465974,15.652028,70.657718
Williamtown,12.820376,24.147020,3.510985,6.957167,7.140044,41.753695,2012.704269,6.397571,15.815511,75.464635
Townsville,20.411250,29.362974,3.488603,7.197113,8.460627,38.804052,2012.724036,6.453347,15.661391,84.853353
NorahHead,15.375197,22.607900,3.382479,NaN,NaN,42.215043,2012.804712,6.391260,15.688290,72.694220
Sydney,14.865057,23.002339,3.330231,5.187432,7.179374,41.761408,2012.300869,6.453102,15.665868,73.404210
MountGinini,3.651193,11.777947,3.245241,NaN,NaN,46.188214,2012.835225,6.463364,15.654627,53.200304
Brisbane,16.410998,26.441527,3.160536,5.408848,8.082782,28.211380,2012.496678,6.547928,15.727934,79.594748
Newcastle,13.740240,24.098283,3.153022,NaN,NaN,NaN,2012.706599,6.487310,15.662267,75.376909
NorfolkIsland,16.839960,21.792746,3.137568,4.738026,7.021751,42.639973,2012.724696,6.413630,15.622470,71.226943
Katherine,20.534983,34.939037,3.135599,7.333198,NaN,38.758328,2014.827453,6.424631,15.603592,94.890267
SydneyAirport,14.894041,23.378902,2.995335,5.252450,7.198126,47.222072,2012.774709,6.420965,15.645923,74.082023
Witchcliffe,10.756861,21.699423,2.899658,NaN,NaN,39.980259,2012.781504,6.428523,15.653794,71.058962
Walpole,11.915711,20.566821,2.877329,NaN,NaN,39.753051,2012.819794,6.359347,15.650585,69.020277
Portland,9.585537,18.055626,2.531032,3.421514,6.496751,42.058883,2012.778037,6.415554,15.661883,64.500127
Albany,12.948461,20.072587,2.255073,4.207273,6.658765,NaN,2012.708554,6.451592,15.641910,68.130657
BadgerysCreek,11.136900,24.023111,2.207925,NaN,NaN,33.609890,2012.790984,6.402322,15.693306,75.241600
Tuggeranong,7.245612,20.777444,2.159040,NaN,NaN,35.189615,2012.741494,6.453969,15.665777,69.399399
Richmond,11.346070,24.449813,2.152581,5.259336,NaN,34.860354,2012.802779,6.426296,15.604880,76.009664
Dartmoor,8.619816,19.694427,2.148554,3.353097,6.412715,38.896904,2012.857628,6.483860,15.724091,67.449969
Penrith,12.533649,24.731984,2.135143,NaN,NaN,31.794386,2012.763158,6.445682,15.647436,76.517571
MountGambier,8.827468,19.828128,2.087359,3.437072,6.511167,42.869099,2012.717822,6.455776,15.668317,67.690631
Launceston,7.833818,18.956231,2.012219,6.166667,NaN,35.630877,2012.723250,6.458388,15.657860,66.121217
Albury,9.520899,22.630963,1.925710,NaN,NaN,32.953016,2012.733643,6.447360,15.711059,72.735734
Perth,12.922706,25.034837,1.906295,5.606579,8.784536,34.882999,2012.504228,6.528656,15.725337,77.062707
Watsonia,10.126228,20.883528,1.847692,4.640788,6.378152,38.057297,2012.770590,6.422808,15.649216,69.590350
Melbourne,11.788127,20.860148,1.837772,4.595893,6.465776,45.425444,2011.949897,6.635318,15.834497,69.548266
PerthAirport,12.580359,25.533234,1.761648,5.662832,8.795306,44.201822,2012.779661,6.419076,15.646726,77.959821
Canberra,6.827688,20.980644,1.735038,4.404717,7.403241,40.082174,2012.164131,6.483616,15.714745,69.765160
WaggaWagga,9.562030,22.961290,1.706085,5.159061,8.197864,36.566147,2012.736559,6.415659,15.642809,73.330323
Ballarat,7.355302,18.274794,1.688830,NaN,NaN,44.978695,2012.732166,6.463012,15.686592,64.894628
PearceRAAF,12.386314,26.271049,1.634354,NaN,8.894160,43.448549,2012.840333,6.347936,15.598479,79.287888
Bendigo,8.591065,21.616683,1.621452,3.851730,NaN,38.849283,2012.723138,6.459459,15.679960,70.910030
Hobart,9.079141,17.866677,1.604273,3.601226,6.578324,47.531398,2012.502196,6.527604,15.728356,64.160019
Moree,12.786255,26.886861,1.603296,7.629964,8.896590,39.799425,2012.688858,6.454800,15.502453,80.396349
Adelaide,12.628368,22.945402,1.572185,5.824924,7.752002,36.530812,2012.525890,6.522330,15.742071,73.301723
Sale,8.561220,20.271024,1.512667,3.830098,6.683663,42.474529,2012.771000,6.415000,15.666333,68.487843
MelbourneAirport,9.973945,20.491858,1.451977,4.644378,6.381283,46.919172,2012.779661,6.419076,15.646726,68.885344
Nuriootpa,9.366433,21.714658,1.381375,5.084132,7.675888,40.660720,2012.776482,6.414057,15.650899,71.086384
Cobar,13.120342,25.834081,1.129262,6.720797,8.674364,36.728814,2012.766064,6.410977,15.619143,78.501346
SalmonGums,9.302578,24.249204,1.032302,NaN,NaN,39.761086,2012.814552,6.429442,15.642301,75.648567
Mildura,10.733954,24.841536,0.945025,5.935952,8.468104,37.170829,2012.778849,6.420353,15.642833,76.714766
Nhil,8.992798,22.398407,0.932907,NaN,NaN,42.542438,2014.838751,6.418738,15.687699,72.317132
AliceSprings,13.125182,29.244191,0.869355,9.029929,9.581944,40.533714,2012.719565,6.451006,15.645661,84.639545
Uluru,14.406983,30.387442,0.707324,NaN,NaN,41.369231,2014.852728,6.468113,15.691650,86.697396
Woomera,13.313898,26.542135,0.489946,10.116654,9.063005,44.080962,2012.773579,6.402676,15.634448,79.775843

In [74]:
data_by_loction = data.groupby(by= ["Month"]).mean(numeric_only= True)

In [76]:
data_by_loction.head()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,year,Day,maxtemp_f
Month,,,,,,,,,
1,15.617757,27.257839,2.824303,7.485814,8.600858,42.210562,2012.936444,16.182338,81.064110
2,14.992372,26.163534,2.730953,6.576706,8.206513,40.315826,2012.933129,14.420945,79.094361
3,14.215426,25.151477,2.626832,5.758783,7.505240,39.390425,2012.928052,16.236535,77.272658
4,12.201043,23.127578,2.429550,4.704796,7.305555,37.628524,2013.071753,15.324372,73.629641
5,10.388750,20.912700,2.279773,3.960461,6.617251,37.147284,2012.943615,16.235489,69.642860

- sometime feling cold is more then about low temp.,a windaly day can also make you cold factor called 
- the chill factor can used quntify cold based the wind the temp.the farmula the chill factor given by
- WCI = (10*sqrt(v)- 10.5).(33-temp.)
- v the speed the wind and temp. is the maxmumtemp.
- add the colum wci and find the month with the lowest WCI

In [78]:
from math sqrt

SyntaxError: invalid syntax (1210907700.py, line 1)

In [81]:
from math import sqrt

def wci (x):
    v = x["WindGustSpeed"]
    minTemp	= x["MinTemp"]
    return ((10*sqrt(v)-v+10.5)*33- minTemp)

In [82]:
data["WCI"] = data.apply(wci,axis = 1)

In [83]:
data.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,year,Month,Day,maxtemp_f,Is_raning,WCI
0,01-12-2008,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,2008,1,12,73.22,barish_nahi_hoti,1070.072362
1,02-12-2008,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,2008,2,12,77.18,barish_nahi_hoti,1076.072362
2,03-12-2008,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,2008,3,12,78.26,barish_nahi_hoti,1053.768894
3,04-12-2008,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,2008,4,12,82.40,barish_nahi_hoti,1161.963230
4,05-12-2008,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,2008,5,12,90.14,barish_nahi_hoti,1089.030998